### ISSUE TITLE
Errore battitura

### ISSUE THREAD

**Issue by KibGim** [italia/lg-patrimonio-pubblico#12]
https://github.com/italia/lg-patrimonio-pubblico/blob/505532c2f67c02977f5177517186aec6c588ca3e/rst/arch.rst#formati-aperti-per-i-documenti
correggere "lil" con "il"
> p) documento informatico: **_lil_** documento elettronico

**Comment by giorgialodi** [comment]
Ciao @KibGim l'errore di battitura è stato corretto. Grazie per la segnalazione. Ciao, G.
