### ISSUE TITLE
URL da modificare

### ISSUE THREAD

**Issue by aborruso** [italia/lg-patrimonio-pubblico#15]
Buon pomeriggio in [questa pagina](https://www.agid.gov.it/it/agenzia/stampa-e-comunicazione/notizie/2017/08/03/open-data-online-linee-guida-valorizzazione-del-patrimonio-informativo-pubblico)  c'è il puntamento alla versione bozza (e non alla stabile) delle "Linee guida nazionali per la valorizzazione del patrimonio informativo pubblico".

O meglio l'URL http://lg-patrimonio-pubblico.readthedocs.io/it/latest ha un redirect verso https://docs.italia.it/italia/daf/lg-patrimonio-pubblico/it/bozza/  e non verso https://docs.italia.it/italia/daf/lg-patrimonio-pubblico/it/stabile/

**Comment by giorgialodi** [comment]
Ciao @aborruso  sì hai ragione, mi coordino con  @pdavide che segue il lavoro su docs.italia e cerchiamo di risolvere la cosa. Grazie per la segnalazione!

**Comment by giorgialodi** [comment]
@aborruso ci siamo confrontati e con @pdavide. Davide agirà per correggere il link nel sito di AgID da te segnalato. Grazie!

**Comment by aborruso** [comment]
Grazie

**Comment by pdavide** [comment]
@giorgialodi notizia su sito AGID corretta. Puoi chiedere la issue.

**Comment by aborruso** [comment]
grazie @pdavide
